language: python
python:
  - "2.7"
  - "3.7"
  - "3.8"

install:
  - pip install -r "requirements.txt"

script:
  - pylint-check --pylint
  - pylint-code-rating-check --pylint
  - pylint-docstring-check --pylint

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
#before_install:
#install:
#before_script:
#script:
#after_success:
#after_failure:
#after_script:
#before_deploy:
#deploy:
#after_deploy:
